### ISSUE TITLE
Unable to load UTF8-BOM files

### ISSUE THREAD

**Issue by Teu3hgb** [exectails/Mabioned#1]
This editor assumes that the game is using UTF16-BOM, however some versions of the game actually use UTF8-BOM instead.

As a result, it isnt possible to load the XML files and whatnot for versions of the game that use UTF8-BOM.

Here is a picture of the problem:
https://i.imgur.com/GCitaLz.png

**Comment by exectails** [comment]
Thank you for reporting this issue, it's fixed in the master branch now. Apparently C# refuses to read an XML file as UTF8 if the XML's header says the file is using UTF16, even though you have to wonder how it even read that without using UTF8^^ I guess ultimately it's the fault of whoever saved it as UTF8 without changing the header.

May I ask which client you are using where this file was not using Unicode?

**Comment by Teu3hgb** [comment]
MabiPro client is using UTF8-BOM instead of UTF16-BOM.
