### ISSUE TITLE
Unable to open Courcle region 

### ISSUE THREAD

**Issue by Teu3hgb** [exectails/Mabioned#2]
Attempting to open the file `iria_c_main_field/iria_c_main_field.rgn` from ~G13~ any version results in an obscure error:
https://i.imgur.com/ZP7DzhU.png

Tested on the latest master commit 9d341844d2f79a689568f457a28150acdbccce49.

**Comment by Teu3hgb** [comment]
Tested on the latest NA client file and the exact same error occurs (same numbers and all).

**Comment by Teu3hgb** [comment]
iria_se_main_field appears to have the same error.

**Comment by Teu3hgb** [comment]
If it matters at all, G17 appears to have the same problem as well.

**Comment by exectails** [comment]
Thank you for your report, unfortunately I can't reproduce this. Both regions you mentioned open normally for me, and they both have the expected 4 byte tail.

To explain what the error means, there's some seemingly random data at the end of some region files, the "tail", and for most regions it's 4 byte long. I don't think the problem here is the client files or Mabioned specifically.

**Comment by Teu3hgb** [comment]
I am able to reproduce it on multiple different machines, with my own build and your public release build. 
(Windows 7 with .NET 4.6.2, and Windows 10 with .NET 4.6.2)

Do you have any ideas why it doesn't reproduce for you?

**Comment by exectails** [comment]
I do, I just tested the G13 files, and there I did get the error^^ `iria_c_main_field` actually is different from the latest NA version of the region. It's random garbage again, a copy of a part of the rest of the file.

Since I can't check for the G13 files specifically I've excluded the check from the Release build. You will only get that error for the region now if you compile in Debug mode. I actually assume that we could discard that tail, as it clearly looks like an error that the data is even there, but I want to keep it around for now, just in case.

**Comment by Teu3hgb** [comment]
Thanks. I can open the files now. 
However, just in case this is relevant in the future: I would like to mention again that this happens with G17 files as well for the following regions:
iria_c_main_field,  iria_se_main_field,  tara_main_field
