### ISSUE TITLE
Renaming .areas does not save new names properly

### ISSUE THREAD

**Issue by Teu3hgb** [exectails/Mabioned#3]
If you attempt to rename .area files, it will save the new name in the .AREA and filename, but it will **not** save the new name in the .RGN as it should.

This results in an error when you re-open the .RGN file, as the .AREA file no longer exists since it was renamed.

**Here are steps to reproduce:**
1. Open any region.
2. Select an area.
3. Change the "name" field to something else.
4. Save the region.

You will see that after saving the region, the .area file is renamed but it will not save the listing of areas in the region.

**Comment by exectails** [comment]
Thanks you for this report. You're right that the area names in the region file should be updated, not only because that's what you would expect to happen, but also because I hid the area file name list from the edtior, which means you wouldn't even be able to fix/update it if you wanted to.

I kinda glossed over this issue for the time being because I didn't expect anyone to rename areas^^ It's now fixed in the master branch.
